[misc] feat: init random model supports custom code in the model (#4217)
### What does this PR do?

> Add **concise** overview of what this PR aims to achieve or
accomplish. Reference related GitHub issues and PRs that help with the
review.

We should set `trust_remote_code` to True and init model with
`AutoModelForCausalLM.from_pretrained` instead, so that the models that
require custom code to work can still be modified without any error.

e.g. for Kimi K2, without this change, we will get the following error
as Kimi has some custom model handling code in their repo:

```logs
Traceback (most recent call last):
  File "verl/scripts/init_random_model.py", line 93, in <module>
    init_random_model(
  File "verl/scripts/init_random_model.py", line 83, in init_random_model
    model = AutoModelForCausalLM.from_config(new_confg)
  File "transformers/models/auto/auto_factory.py", line 456, in from_config
    return model_class._from_config(config, **kwargs)
  File "transformers/modeling_utils.py", line 277, in _wrapper
    return func(*args, **kwargs)
  File "transformers/modeling_utils.py", line 2311, in _from_config
    model = cls(config, **kwargs)
  File "transformers/models/deepseek_v3/modeling_deepseek_v3.py", line 611, in __init__
    self.model = DeepseekV3Model(config)
  File "transformers/models/deepseek_v3/modeling_deepseek_v3.py", line 533, in __init__
    [DeepseekV3DecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
  File "transformers/models/deepseek_v3/modeling_deepseek_v3.py", line 533, in <listcomp>
    [DeepseekV3DecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
  File "transformers/models/deepseek_v3/modeling_deepseek_v3.py", line 454, in __init__
    self.self_attn = DeepseekV3Attention(config=config, layer_idx=layer_idx)
  File "transformers/models/deepseek_v3/modeling_deepseek_v3.py", line 343, in __init__
    self.qk_head_dim = config.qk_head_dim
  File "transformers/configuration_utils.py", line 207, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'DeepseekV3Config' object has no attribute 'qk_head_dim'. Did you mean: 'v_head_dim'?
```

After this change, everything works fine and we can still get the
correct dummy model (though you are still likely need to manually copy
some code files, e.g. `modeling_deepseek.py`), e.g., via:

```bash
python scripts/init_random_model.py \
--hf_model_path /models/Kimi-K2-Instruct-0905 \
--new_config_path tests/special_e2e/ppo_trainer/expert_parallel/qwen2moe_minimal.json \
--output_path /dummy_models/moonshotai/Kimi-K2-Instruct-0905
--trust_remote_code
```

We get:
```logs
$ du -sh /models/Kimi-K2-Instruct-0905/
959G    /models/Kimi-K2-Instruct-0905/
$ du -sh /dummy_models/moonshotai/Kimi-K2-Instruct-0905
26G     /dummy_models/moonshotai/Kimi-K2-Instruct-0905
$  ls /dummy_models/moonshotai/Kimi-K2-Instruct-0905
chat_template.jinja        model-00001-of-00006.safetensors  model-00005-of-00006.safetensors  tiktoken.model
config.json                model-00002-of-00006.safetensors  model-00006-of-00006.safetensors  tokenization_kimi.py
configuration_deepseek.py  model-00003-of-00006.safetensors  model.safetensors.index.json      tokenizer_config.json
generation_config.json     model-00004-of-00006.safetensors  special_tokens_map.json
```
```python
# Add code snippet or script demonstrating how to use this
```

### Checklist Before Starting

- [X] Search for similar PRs. Paste at least one query link here: ...
- [X] Format the PR title as `[{modules}] {type}: {description}` (This
will be checked by the CI)
- `{modules}` include `fsdp`, `megatron`, `sglang`, `vllm`, `rollout`,
`trainer`, `ci`, `training_utils`, `recipe`, `hardware`, `deployment`,
`ray`, `worker`, `single_controller`, `misc`, `perf`, `model`, `algo`,
`env`, `tool`, `ckpt`, `doc`, `data`
- If this PR involves multiple modules, separate them with `,` like
`[megatron, fsdp, doc]`
  - `{type}` is in `feat`, `fix`, `refactor`, `chore`, `test`
- If this PR breaks any API (CLI arguments, config, function signature,
etc.), add `[BREAKING]` to the beginning of the title.
  - Example: `[BREAKING][fsdp, megatron] feat: dynamic batching`

### Test

> For changes that can not be tested by CI (e.g., algorithm
implementation, new model support), validate by experiment(s) and show
results like training curve plots, evaluation results, etc.

See above

### API and Usage Example

> Demonstrate how the API changes if any, and provide usage example(s)
if possible.

### Design & Code Changes

> Demonstrate the high-level design if this PR is complex, and list the
specific changes.

### Checklist Before Submitting

> [!IMPORTANT]
> Please check all the following items before requesting a review,
otherwise the reviewer might deprioritize this PR for review.

- [X] Read the [Contribute
Guide](https://github.com/volcengine/verl/blob/main/CONTRIBUTING.md).
- [X] Apply [pre-commit
checks](https://github.com/volcengine/verl/blob/main/CONTRIBUTING.md#code-linting-and-formatting):
`pre-commit install && pre-commit run --all-files --show-diff-on-failure
--color=always`
- [ ] Add / Update [the
documentation](https://github.com/volcengine/verl/tree/main/docs).
- [ ] Add unit or end-to-end test(s) to [the CI
workflow](https://github.com/volcengine/verl/tree/main/.github/workflows)
to cover all the code. If not feasible, explain why: ...
- [ ] Once your PR is ready for CI, send a message in [the `ci-request`
channel](https://verl-project.slack.com/archives/C091TCESWB1) in [the
`verl` Slack
workspace](https://join.slack.com/t/verl-project/shared_invite/zt-3855yhg8g-CTkqXu~hKojPCmo7k_yXTQ).
(If not accessible, please try [the Feishu group
(飞书群)](https://applink.larkoffice.com/client/chat/chatter/add_by_link?link_token=772jd4f1-cd91-441e-a820-498c6614126a).)

Signed-off-by: Hollow Man <hollowman@opensuse.org>